/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jelo
 */
public class CalculatorV3 extends javax.swing.JFrame {
    
    static double num1, num2;
    static String op;
    boolean decimal = false;
    
    /**
     * Creates new form CalculatorV3
     */
    public CalculatorV3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNumber = new javax.swing.JTextField();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNumber.setEditable(false);
        tfNumber.setBackground(new java.awt.Color(238, 236, 232));
        tfNumber.setFont(new java.awt.Font("Digital Numbers", 1, 33)); // NOI18N
        tfNumber.setForeground(new java.awt.Color(51, 51, 51));
        tfNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 70));

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/0.png"))); // NOI18N
        btn0.setBorder(null);
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setFocusPainted(false);
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/0.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, 50));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/1.png"))); // NOI18N
        btn1.setBorder(null);
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setFocusPainted(false);
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/1.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 50));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/2.png"))); // NOI18N
        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setFocusPainted(false);
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/2.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 50, 50));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/3.png"))); // NOI18N
        btn3.setBorder(null);
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setFocusPainted(false);
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/3.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 50, 50));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/4.png"))); // NOI18N
        btn4.setBorder(null);
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setFocusPainted(false);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/4.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/5.png"))); // NOI18N
        btn5.setBorder(null);
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setFocusPainted(false);
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/5.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 50, -1));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/6.png"))); // NOI18N
        btn6.setBorder(null);
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setFocusPainted(false);
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/6.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 50, -1));

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/7.png"))); // NOI18N
        btn7.setBorder(null);
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setFocusPainted(false);
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/7.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/8.png"))); // NOI18N
        btn8.setBorder(null);
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setFocusPainted(false);
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/8.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 50, -1));

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/9.png"))); // NOI18N
        btn9.setBorder(null);
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setFocusPainted(false);
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/9.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/clear.png"))); // NOI18N
        btnClear.setBorder(null);
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.setFocusPainted(false);
        btnClear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/clear.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btnBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/backspace.png"))); // NOI18N
        btnBackspace.setBorder(null);
        btnBackspace.setBorderPainted(false);
        btnBackspace.setContentAreaFilled(false);
        btnBackspace.setFocusPainted(false);
        btnBackspace.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/backspace.png"))); // NOI18N
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, -1));

        btnSquareRoot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/square.png"))); // NOI18N
        btnSquareRoot.setBorder(null);
        btnSquareRoot.setBorderPainted(false);
        btnSquareRoot.setContentAreaFilled(false);
        btnSquareRoot.setFocusPainted(false);
        btnSquareRoot.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/square.png"))); // NOI18N
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });
        getContentPane().add(btnSquareRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, -1));

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/minus.png"))); // NOI18N
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setFocusPainted(false);
        btnMinus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/minus.png"))); // NOI18N
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 50, -1));

        btnMultiply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/multiply.png"))); // NOI18N
        btnMultiply.setBorder(null);
        btnMultiply.setBorderPainted(false);
        btnMultiply.setContentAreaFilled(false);
        btnMultiply.setFocusPainted(false);
        btnMultiply.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/multiply.png"))); // NOI18N
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 50, -1));

        btnDivide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/divide.png"))); // NOI18N
        btnDivide.setBorder(null);
        btnDivide.setBorderPainted(false);
        btnDivide.setContentAreaFilled(false);
        btnDivide.setFocusPainted(false);
        btnDivide.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/divide.png"))); // NOI18N
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 50, -1));

        btnDecimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/decimal.png"))); // NOI18N
        btnDecimal.setBorder(null);
        btnDecimal.setBorderPainted(false);
        btnDecimal.setContentAreaFilled(false);
        btnDecimal.setFocusPainted(false);
        btnDecimal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/decimal.png"))); // NOI18N
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 50));

        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/plus.png"))); // NOI18N
        btnPlus.setBorder(null);
        btnPlus.setBorderPainted(false);
        btnPlus.setContentAreaFilled(false);
        btnPlus.setFocusPainted(false);
        btnPlus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/plus.png"))); // NOI18N
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 50, 110));

        btnEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnDefault/equal.png"))); // NOI18N
        btnEqual.setBorder(null);
        btnEqual.setBorderPainted(false);
        btnEqual.setContentAreaFilled(false);
        btnEqual.setFocusPainted(false);
        btnEqual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnRollover/equal.png"))); // NOI18N
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        tfNumber.setText(tfNumber.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       tfNumber.setText(tfNumber.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       tfNumber.setText(tfNumber.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        tfNumber.setText(tfNumber.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        tfNumber.setText(tfNumber.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        tfNumber.setText(tfNumber.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        tfNumber.setText(tfNumber.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        tfNumber.setText(tfNumber.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        tfNumber.setText(tfNumber.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        tfNumber.setText(tfNumber.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        tfNumber.setText(tfNumber.getText() + ".");
        decimal = true;
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        op = "plus";
        num1 = Double.parseDouble(tfNumber.getText());
        tfNumber.setText("");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        op = "minus";
        num1 = Double.parseDouble(tfNumber.getText());
        tfNumber.setText("");
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        op = "multiply";
        num1 = Double.parseDouble(tfNumber.getText());
        tfNumber.setText("");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        op = "divide";
        num1 = Double.parseDouble(tfNumber.getText());
        tfNumber.setText("");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
        String answer;
        double root;
        num1 = Integer.parseInt(tfNumber.getText());        
        root = Math.sqrt(num1);
        
        if(decimal == true)
                tfNumber.setText(String.valueOf(root));
            else
            {
                answer = String.format("%.0f", root);
                tfNumber.setText(answer);
            }
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        double result;                
        String answer = "";
        num2 = Double.parseDouble(tfNumber.getText());         
        
        if(op == "plus")
        {
            result = num1 + num2;
            if(decimal == true)
                tfNumber.setText(String.valueOf(result));
            else
            {
                answer = String.format("%.0f", result);
                tfNumber.setText(answer);
            }                
        }            
        
        if(op == "minus")
        {
            result = num1 - num2;
            if(decimal == true)
                tfNumber.setText(String.valueOf(result));
            else
            {
                answer = String.format("%.0f", result);
                tfNumber.setText(answer);
            }                
        }
        
        if(op == "multiply")
        {
            result = num1 * num2;
            if(decimal == true)
                tfNumber.setText(String.valueOf(result));
            else
            {
                answer = String.format("%.0f", result);
                tfNumber.setText(answer);
            }                
        }
        
        if(op == "divide")
        {
            result = num1 / num2;
            if(decimal == true)
                tfNumber.setText(String.valueOf(result));
            else
            {
                answer = String.format("%.0f", result);
                tfNumber.setText(answer);
            }
        } 
        
        decimal = false;
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        tfNumber.setText(tfNumber.getText().substring(0, tfNumber.getText().length() - 1));
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfNumber.setText("");
        num1 = 0;
        num2 = 0;
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorV3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorV3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfNumber;
    // End of variables declaration//GEN-END:variables
}
